---
name: Build test

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master
      - my_avahi

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-24.04
    concurrency:
      group: ${{ github.workflow }}-${{ toJSON(matrix.env) }}-${{ github.ref }}
      cancel-in-progress: true
    strategy:
      fail-fast: false
      matrix:
        env:
          - { CC: "gcc", DISTCHECK: "true", VALGRIND: "true" }
          - { CC: "gcc", ASAN_UBSAN: "true" }
          - { CC: "clang", ASAN_UBSAN: "false" }
          - { CC: "clang", ASAN_UBSAN: "true" }
    env: ${{ matrix.env }}
    steps:
      - name: Repository checkout
        uses: actions/checkout@v4
      - run: sudo -E .github/workflows/build.sh install-build-deps
      - run: sudo -E .github/workflows/build.sh build
  coverage:
    if: github.repository == 'avahi/avahi'
    runs-on: ubuntu-24.04
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true
    permissions:
      contents: read
      checks: write
    env:
      CC: "gcc"
      COVERAGE: "true"
    steps:
      - name: Repository checkout
        uses: actions/checkout@v4
      - run: sudo -E .github/workflows/build.sh install-build-deps
      - run: sudo -E .github/workflows/build.sh build
      - name: Coveralls
        uses: coverallsapp/github-action@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          file: ./coverage.info
          format: lcov

  freebsd:
    runs-on: ubuntu-24.04
    steps:
      - name: Repository checkout
        uses: actions/checkout@v4
      - uses: cross-platform-actions/action@a0672d7f6de3a78e7784bbaf491c7303f68d94b3 # v0.26.0
        with:
          operating_system: 'freebsd'
          version: '14.2'
          architecture: 'x86_64'
          run: |
            export CC=clang
            sudo -E pkg install -y gettext-runtime gettext-tools gmake intltool \
            gobject-introspection pkgconf expat libdaemon dbus-glib dbus gdbm \
            libevent glib automake libtool qt5-core qt5-buildtools gtk3 \
            py311-pygobject py311-dbus py311-gdbm
            sudo pkg remove -f avahi-app
            sudo -E .github/workflows/build.sh build
